### ISSUE TITLE
Group Manager Permissions not working

### ISSUE THREAD

**Issue by anis-bedhiafi** [fusionpbx/fusionpbx#1065] opened 2015-07-26 13:28 UTC
Creating a New group in Advanced > Group Manager and setting permissions to the new group are not working.

My configuration:
FusionPBX: 3.9.0 with Postgres 9 on Ubuntu 14.04 LTS
I used the install script from Github (https://raw.githubusercontent.com/fusionpbx/fusionpbx-scripts/master/install/ubuntu/install_fusionpbx.sh)

Here is how I do:

- Go to Advanced > Group Manager and create a new group (set it Global or for the current domain)
- Define Permissions for the new group
- Go to Advanced > Menu Manager and define the menu items for the group
- Go to Accounts > User Manager and create a new user and affect it to the new group.
- Log out and login with the new user
- Strange behavior, the new user can create extensions but cannot see them (only the superadmin can), follow me is not working in the new user account, Extension Summary, Conferences can be created but not shown.
NOTICE: I am sure that I defined all permissions for the above apps

Please help me on this one. What could be the problem? is it from my installation on Ubuntu server or Postgres or what? Am I missing something? Anyone who faced the same problem?

I opened a ticket for this before  #1028 but no answers
@richbreton can you help with this one?

**Comment by anis-bedhiafi** [comment] 2015-07-27 12:02
I even followed instaructions by word on https://github.com/fusionpbx/fusionpbx
using Debian Jessie PostgreSQL and Nginx but still facing the same problem while creating a new group with different permissions.

Please help what could be the problem?

**Comment by moteus** [comment] 2015-07-27 12:33
Hello.
First at all I am not expert on FusionPBX but just newbie user.
I have installed current master version on Windows and I can not reproduce problem.
What I do
 * create new group in domain (I have 2 domain in FPBX)
 * Check all permissions on `Extension` group in Group Manager
 * add this group to menu `Account->Extension`
 * Create new user and assign his to group.
 * Login as this user and I can see all existed Extensions as well as create new one.

**Comment by anis-bedhiafi** [comment] 2015-07-27 12:38
Thank you @moteus for the reply.
What about conference center can you create a new conference and see it using this new user?

**Comment by moteus** [comment] 2015-07-27 13:01
I can add new conf but I can not see it because of

```PHP
if (if_group("superadmin") || if_group("admin")) {
	//show all extensions
	$sql = "select * from v_conference_centers ";
	$sql .= "where domain_uuid = '".$_SESSION['domain_uuid']."' ";
}
else {
	//show only assigned extensions
	$sql = "select * from v_conference_centers as c, v_conference_center_users as u ";
	$sql .= "where c.conference_center_uuid = u.conference_center_uuid ";
	$sql .= "and c.domain_uuid = '".$_SESSION['domain_uuid']."' ";
	$sql .= "and u.user_uuid = '".$_SESSION['user_uuid']."' ";
}
```
I do not know what does mean ` assigned extensions`, but I think this is bug because I can not find whre  v_conference_center_users is filled.  It comment out in `conference_center_edit.php`.
Or this just not yet immplemented feature.

**Comment by anis-bedhiafi** [comment] 2015-07-27 14:43
Yes I found how it works. For example if I want to add a new group called "TestGroup"
I have to add in app.conf a condition here
if (if_group("superadmin") || if_group("admin") || if_group("TestGroup")) {

the same thing applies for all aps

**Comment by markjcrane** [comment] 2015-07-27 21:01
Permissions should be used 99% of the time with rare exceptions. So I updated conference center to use permissions instead of groups.

**Comment by anis-bedhiafi** [comment] 2015-07-27 22:14
Thank you so much @markjcrane 
But note that the same problem of permissions is faced with:
NOTE: BEFORE STARTING, I MADE SURE THAT ALL PERMISSIONS ARE CHECKED FOR THE NEW GROUP AND THE NEW USER CAN DO ANYTHING.

- Accounts > Extensions ( while creating an extension if I click Save button it says Access Denied but the extension is although created). 
- Apps > Follow Me (Not displaying anything even though I have several Extensions)
- Apps > Operator Panel (while issuing calls nothing is indicating that anyone is calling or is receiving a call)
- Status > Extension Summary (Nothing is displayed)

**Comment by anis-bedhiafi** [comment] 2015-07-28 08:13
I fixed Follow Me permissions problem by doing the following:
- In apps/calls/calls.php:

-if (!(if_group("admin") || if_group("superadmin"))) {         (line 64)
+if (permission_exists('follow_me') || permission_exists('call_forward') || permission_exists('do_not_disturb')) {

**Comment by badcrc** [comment] 2015-09-07 14:19
I stumbled into the same problems here and hopefully fixed a couple of them.

But for xml_cdr_extension_summary.php IMHOI would use 'xml_cdr_view' instead 'xml_cdr_all'.

With "xml_cdr_all", you have permissions to view all the extensions, and in a MT scenario it would be too much.

**Comment by markjcrane** [comment] 2015-09-07 19:47
anis-bedhiafi 

In apps/calls/calls.php:

-if (!(if_group("admin") || if_group("superadmin"))) { (line 64)
+if (permission_exists('follow_me') || permission_exists('call_forward') || permission_exists('do_not_disturb')) {

Sorry I'm not sure you understand the purpose of this code.

The idea with the code on line 64 is to allow an admin or superadmin to see call forward, follow me and DND for all extensions. Your change would make it so that admins and superadmins only see their own extensions.

**Comment by markjcrane** [comment] 2015-09-07 19:51
badcrc
The 'xml_cdr_view' permission is for viewing the call detail records. By default given to the user, admin, and superadmin groups.

This 'xml_cdr_all' permission is meant primarily for superadmins to see CDR across all domains all at once. By default this is given only to the superadmin group. It definitely should not be given to admin group.

**Comment by markjcrane** [comment] 2015-09-07 21:05
badcrc - tested assigning a user to a conference center it worked fine on my server.

**Comment by badcrc** [comment] 2015-09-08 06:15
But doesn't the code in apps/calls/calls.php (and in xml_cdr_extension_summary.php) means that only users members of the group admin & superadmin can view those sections? 

I we make a custom group (which I think is what @anis-bedhiafi is doing, at least is what I'm doing) and assign to an user that user cannot view the section even if they have those permissions assigned.

Having hardcoded "(if_group("admin") || if_group("superadmin")" doesn't limit the groups permissions in a way?

**Comment by markjcrane** [comment] 2015-09-08 06:19
You missed ! (exclamation point) which is actually stating 'not' a member
of that group.

**Comment by badcrc** [comment] 2015-09-08 06:44
OK, I get it now, so the actual logic is that if the user isn't a member of superadmin or admin it needs to have the extensions assigned.

Wouldn't be an improvement if we could also have the option to supersede with the permissions?  
Something like this seems to work:
```
if (!(if_group("admin") || if_group("superadmin")) && !permission_exists('xml_cdr_view')) {
    (...)
}
```

**Comment by markjcrane** [comment] 2015-09-16 04:27
At the top of the file we have already required the 'xml_cdr_view' permission. Adding it again later in the file when its already required is redundant.

**Closed** 2016-08-14 17:02 UTC
