### ISSUE TITLE
Voicemail greeting will not play after being transferred from IVR

### ISSUE THREAD

**Issue by pixel2920** [fusionpbx/fusionpbx#1749] opened 2016-07-12 23:52 UTC
After transferring from IVR, tried the us-ring ringback as mcrane suggested, but neither MoH nor us-ring ringback will play the voicemail greeting after timeout - it immediately starts recording, or sometimes worse, will have already recorded before the caller can say anything.

**Comment by pixel2920** [comment] 2016-07-13 00:00
In the logs, it is already playing, but also says this:

```
2016-07-12 16:46:22.032991 [INFO] switch_ivr_async.c:4065 UnBound A-Leg: ALL
2016-07-12 16:46:22.032991 [DEBUG] switch_cpp.cpp:746 CoreSession::setVariable('playback_terminators', '#')
2016-07-12 16:46:22.052964 [DEBUG] switch_core_file.c:330 File /var/lib/freeswitch/storage/voicemail/default/domain.net/103/greeting_1.wav sample rate 16000 doesn't match requested rate 8000
2016-07-12 16:46:22.052964 [DEBUG] switch_ivr_play_say.c:1467 Codec Activated L16@8000hz 1 channels 20ms
2016-07-12 16:46:22.052964 [DEBUG] switch_ivr_play_say.c:1910 done playing file /var/lib/freeswitch/storage/voicemail/default/domain.net/103/greeting_1.wav
2016-07-12 16:46:22.052964 [DEBUG] switch_ivr_play_say.c:1467 Codec Activated L16@8000hz 1 channels 20ms
2016-07-12 16:46:22.052964 [DEBUG] switch_ivr_play_say.c:1910 done playing file silence_stream://200
2016-07-12 16:46:22.052964 [DEBUG] switch_ivr_play_say.c:1467 Codec Activated L16@8000hz 1 channels 20ms
2016-07-12 16:46:22.052964 [DEBUG] switch_ivr_play_say.c:1910 done playing file /usr/share/freeswitch/sounds/en/us/callie/voicemail/vm-record_message.wav
2016-07-12 16:46:22.152979 [DEBUG] switch_cpp.cpp:890 getDigits dtmf_buf:
2016-07-12 16:46:23.152986 [DEBUG] switch_cpp.cpp:890 getDigits dtmf_buf:
```

**Comment by samael33** [comment] 2016-07-13 13:08
May be a bit strange - try to change ringback tone from us-ring to ca-ring.

**Comment by pixel2920** [comment] 2016-07-13 20:44
Clarification: only happens from a DID.  Internal extension/direct dial from extension to IVR or voicemail is OK.

**Comment by samael33** [comment] 2016-07-13 20:51
I faced same issue with a more complex routing, but it always resolved with ringback type changing. Seems it's not a fusion, but freeswitch issue.

**Comment by pixel2920** [comment] 2016-07-13 20:52
I've tried two different ringback type schemes though...it says something about wrong bitrate.  Where to look there?

**Comment by samael33** [comment] 2016-07-13 20:53
Look in the logs )
But anyway - try to upload your sound as MoH and set different ringback.

**Comment by pixel2920** [comment] 2016-07-13 20:55
Sorry - asked the wrong question...the logs are above.  What can I do about those messages?  And I'm using the default MoH music.

**Comment by DigiDaz** [comment] 2016-07-13 21:23
Though I do not know the cause, a temporary fix is to edit the play_greeting.lua voicemail function.

Near the bottom of the file you will see after an else:  

session:streamFile(voicemail_dir.."/"..voicemail_id.."/greeting_"..greeting_id..".wav");

Change it to: 

session:execute("playback",voicemail_dir.."/"..voicemail_id.."/greeting_"..greeting_id..".wav");

The greeting will now play.

**Comment by pixel2920** [comment] 2016-07-14 22:19
This change is successful in fixing it.  Awaiting guidance from mcrane as to whether if or how this code will make it into the default app scripts/lua.

**Comment by markjcrane** [comment] 2016-07-15 14:45
Thanks DigiDaz for the suggestion.
https://github.com/fusionpbx/fusionpbx/commit/2373b38630822a0adbaae1b926cb6b178100d536

**Closed by markjcrane** 2016-07-15 14:45 UTC

**Comment by pixel2920** [comment] 2016-07-19 03:50
Bummer. This only fixes voicemail greetings that are not the default.
