### ISSUE TITLE
Call forward endless loop segfaults freeswitch

### ISSUE THREAD

**Issue by lcx** [fusionpbx/fusionpbx#2746] opened 2017-07-18 12:12 UTC
duplicate of #2481 but this issue happens with newer versions as well. 

installed a new testsystem from master some weeks ago (version 4.2.2)
set up 2 extensions, 6000 and 6001.
Each has a call forward to the other 6000 -> 6001 -> 6000
Call one of the extensions and freeswitch segfaults.

```
[2530312.557827] freeswitch[11036]: segfault at 7fd134133ff8 ip 00007fd16066f5f4 sp 00007fd134133ff0 error 6 in liblua5.2.so.0.0.0[7fd16065e000+31000]
```

I don't think it's a fusionpbx issue, rather a freeswitch issue but it has to be somehow addressed.
Since this just happened again since one of my customers does this several times and forgets about it but if they receive a call on one of those extensions it kills my fusionpbx.
Although the upgrade needs to happen soon, this won't fix this issue.

**Comment by markjcrane** [comment] 2017-07-18 17:00
So you intentionally created an endless loop using forward.

**Comment by DigiDaz** [comment] 2017-07-18 17:04
I think his point is that two users can do this unintentionally.

**Comment by lcx** [comment] 2017-07-24 09:24
yes exactly. I have some users doing this 2x per month. 
User A with extension 10 call forwards to user B with extension 24. 
Now user B (24) for some reason decides to call forward to 10, forgetting that there is a call forward enabled. 
Call comes in -> segfault. 

I have told the users to be more careful about that, but it can happen very easy in larger companies where people tend to forget who is on holiday and that those people have a CF enabled, even if they wanted to check there would be no way except going to that phone and checking if CF is enabled or looking at the web interface which in this case would be to complicated for the users. 
 
I have no clue on how one could prevent this, my biggest problem ist that users can kill your system and being multi tenant they can very easy create a DoS.

**Comment by markjcrane** [comment] 2017-07-25 02:16
How are the users call forwarding the calls on the endpoint (device)? There are multiple types of call forward which is why knowing which one you are referring to is important. So the end of your statement mentioned in the web interface is that correct? The problem is worse if one extension forwards and the next one forwards there is a chance the next one is forwarded. So this prevention would have to be recursive. Or need prevent people from forwarding to some destination that is already forwarded.

**Comment by lcx** [comment] 2017-07-25 13:54
They are creating the CF on the SNOM which is set up to trigger *72+extension. 
I modified the Lua script (I think ..) to accept a extension after *72 and not prompt the user anymore for the final destination, I wrote up my changes here: https://medium.com/@lcx_at/call-forward-with-snom-and-fusionpbx-971538f0e497

but the end result is the same as if the user would have dialed *72 and then entered the destination where the call should be forwarded to or if the CF would have been set up via the Web interface. 
I should retry this with a callforward just set on the phone an not via the Web UI.

**Comment by moteus** [comment] 2017-07-25 14:22
>I modified the Lua script (I think ..) to accept a extension after *72 and not prompt the user anymore for the final destination

I think this feature already exists in current master. Same as BLF monitoring for CF

**Comment by moteus** [comment] 2017-07-28 10:32
https://freeswitch.org/jira/browse/FS-2279

> You can't really use a user/ in a dial-string.. the user/ channel is what uses the dial-string to resolve the user... you're basically creating a loop and busting the stack... thus it will segfault... its recursion .. user/ calls user/ calls user/ calls user/ till its all full and dies. 
>dial-string needs to be something OTHER than user/ cuz thats how user/ resolves the endpoint.

**Comment by konradSC** [comment] 2017-09-19 18:41
My thoughts are to check for a loop in the dialplan. So if a call comes in for a user and the user has call forward always enabled, then run then run the lua. If a loop is detected, then kill the call rather than crashing the entire server. 

This is the lua script i came up with in a pinch. It only checks three extensions deep into a call forward. 
(Example:  x1000 -> x2000 | x2000 -> x3000 | x3000 -> x1000)
[https://github.com/konradSC/Fusionpbx-Public/blob/master/Scripts/Call%20Forward%20Loop%20Detection/call_forward_loop_detection.lua](url)

You would call the script by adding the following to your dialplan: 
`<extension name="cf_loop_detect" continue="true" uuid="xxxxxx">

	<condition field="${user_exists}" expression="^true$">

		<action application="set" data="forward_all_enabled=${user_data ${destination_number}@${domain_name} var forward_all_enabled}" inline="true"/>

	</condition>

	<condition field="${forward_all_enabled}" expression="true">

		<action application="lua" data="call_forward_loop_detection.lua ${destination_number} ${domain_name}"/>

	</condition>

</extension>`

**Comment by lcx** [comment] 2017-09-20 08:21
I would give it a try but something seems to be wrong with the url.

**Comment by moteus** [comment] 2017-09-20 08:35
[call_forward_loop_detection.lua](https://github.com/konradSC/Fusionpbx-Public/blob/master/Scripts/Call%20Forward%20Loop%20Detection/call_forward_loop_detection.lua)

**Comment by markjcrane** [comment] 2017-09-21 01:23
That lua script that KonradSC came up with im sure works but. We talked for a while on the phone about this and think call forward completed without using the dial string might be a better way to fix it.  Using a dialplan I wrote some time ago. Still need more teating to see if it solves the problem. If it works it will solve multiple things not just this.

**Comment by markjcrane** [comment] 2017-09-26 19:17
A while ago I had created a way to do call forward all with a dialplan on the master branch. It required an update to work fully and user_exists variables needed to be set to 'inline'.

This approach an infinite loop is prevented by the max hop count and FreeSWITCH doesn't crash. The new approach has multiple benefits. I've added this to the stable branch.

However this doesn't fix a ring group that goes to the forwarded extension in the loop. So there is more work that needs to be done. My first attempt to solve the problem for ring groups failed.

**Comment by lcx** [comment] 2017-09-27 07:54
awesome! Have to give it a shot on my test environment.

**Comment by konradSC** [comment] 2017-09-27 12:50
What about a "Use Call Routing Rules" option for each ring group member? The default value would be "No", but  if enabled it would honor the Follow Me and Call Forward settings of that member.

**Comment by markjcrane** [comment] 2017-09-27 15:22
KonradSC for the ring group how many levels deep should the forward be followed? Also infinite loop would still need to be detected and prevented.

**Comment by markjcrane** [comment] 2017-10-08 06:40
Fixed the issue and committed to stable and master branches. So now can consider this closed. Talked about this in detail in the new FusionPBX continuing education training.

**Closed by markjcrane** 2017-10-08 06:40 UTC
Labels: bug

**Comment by voiply-fyanko** [comment] 2017-10-19 15:06
Did this get resolved? I don't see the fix in the commit... please advise!

**Comment by markjcrane** [comment] 2017-10-19 15:23
It was resolved in a bunch of commits.
