### ISSUE TITLE
New route does not insert XML into database until second save

### ISSUE THREAD

**Issue by tannermkerr** [fusionpbx/fusionpbx#1982] opened 2016-10-11 19:28 UTC
I'm using fusionpbx with postgres.
I've found that when I delete, then recreate an outbound route with the same settings, calls stop working. When I looked into it I found that the db column 'dialplan_xml' in v_dialplans was empty upon creation for the outbound route I just created. When I saved the route again, without changing anything, the xml was inserted, and the outgoing calls began to work again.

**Comment by andycol** [comment] 2016-10-12 06:12
i have the same issue

**Comment by andycol** [comment] 2016-10-14 12:01
this is a major issue, and i notice sometimes you have to go into the outbound route, make a change then click save, then revert the change and save again before it works

**Comment by markjcrane** [comment] 2016-10-14 15:09
These bugs have occurred on the development branch because of a major change.
However I fixed outbound routes, inbound routes, time conditions, and conferences this morning. All of the remaining ones that I'm aware of.  Please update and test and report back and close the issue once you have confirmed it is fixed.

**Comment by andycol** [comment] 2016-10-14 16:06
thanks i will test 👍  but i am on the master branch, is that the development branch?

**Comment by markjcrane** [comment] 2016-10-14 16:17
Yes master is the development branch

**Comment by andycol** [comment] 2016-10-14 16:21
how do i go to the stable branch as this is my production system

**Comment by markjcrane** [comment] 2016-10-22 00:23
These bugs are all fixed.

**Comment by markjcrane** [comment] 2016-10-22 00:24
andycol
mv /var/www/fusionpbx /var/www/fusionpbx-master
git clone -b 4.2 https://github.com/fusionpbx/fusionpbx.git
cp /var/www/fusionpbx-master/resources/config.php /var/www/fusionpbx/resources
chown -R www-data:www-data /var/www/fusionpbx

**Closed by markjcrane** 2016-10-22 00:24 UTC
