### ISSUE TITLE
NotABug. SOLVED New Install (trunk, 4.2) Cannot Login

### ISSUE THREAD

**Issue by rossbcan** [fusionpbx/fusionpbx#2003] opened 2016-10-18 15:36 UTC
Brain trouble compounded by freeswitch / fusionpbx behavioral changes.

If configured with domain (as opposed to IP address):

old login: user, password
new login: user@domain, password

Hi;
Linux x86_64
PHP 5.4.27
freeswitch 1.6.11
sqlite3
for now, everything as root, permissions OK

Starting from both Git(trunk) and zip(4.2), fusionpbx, at completion of GUI configure (had to increase webserver script_timeout to avoid "Bad Gateway"), cannot login (Invalid user...).

PHP shows these errors:
PHP Warning:  Illegal string offset 'en-us' in /usr/local/fusionpbx/core/install/install.php on line 260
PHP Fatal error:  Call to a member function execute() on a non-object in /usr/local/fusionpbx/resources/classes/menu.php on line 441

The second error seems to indicate some sort of database connection problem, although I can inspect the database with sqlite3 and, it was created. Further, if I (sqlite3) do ".dump v_users", the user ID and password are correct (used MD5 password generator with salt to verify password).

I have gone through this install cycle multiple times, with same result:

- stop freeswitch
- replace  .../etc/freeswitch (config dir) with pre-fusionpbx snapshot
- re-install fusionpbx directory (or, delete fusionpbx/resources/config.php, fusionpbx/secure/fusionpbx.db)
- start freeswitch
- invoke web configuration GUI, allow to complete.
- Login prompt appears, after enter user, pass: always "Invalid User..."

I had this installation previously working with fusionpbx trunk from 20160311 and freeswitch 1.4.18
What has changed is freeswitch to V1.6.11 and fusionpbx version.

Is this a bug, or, am I missing something?

I can temporarily allow SSH access to this installation, if required and someone is interested.

Please note: I cannot go to a "supported" linux distribution. This is is part of a more comprehensive server appliance.

Suggestions?, tests to do...

rossbcan uNoWhat gmail.com
Thanks;
Bill

**Comment by markjcrane** [comment] 2016-10-18 22:51
Since now the title shows solved closing the issue.

**Closed** 2016-10-18 22:51 UTC

**Comment by hpandroid** [comment] 2017-04-09 21:47
Hi Rossbcan,

I also running through same issue, it is giving me error at menu.php line 441. even when ever i try to edit any of dial panel through UI it is giving me 
Fatal error: Uncaught Error: Cannot use string offset as an array in C:\inetpub\wwwroot\fusionpbx\app\dialplan\dialplan_edit.php:249 Stack trace: #0 {main} thrown in C:\inetpub\wwwroot\fusionpbx\app\dialplan\dialplan_edit.php on line 249


Please help me.

Thanks,
Harry

**Comment by rossbcan** [comment] 2017-04-09 22:33
Hi Harry;

 

As I recall, the issue was (upgrading fusionpbx) logon name changed

Old: login name

New: login name@configured domain

 

Anything, else, you will have to refresh my memory (link to issue)

 

Bill

**Comment by markjcrane** [comment] 2017-04-09 22:33
Harry what operating system and how dido you do the install?

**Comment by DigiDaz** [comment] 2017-04-09 23:27
Harry, looks like he is windows and maybe microsofts webserver.

**Comment by tonyhain** [comment] 2017-04-12 22:22
Happens on FreeBSD-11 as well. FreeSWITCH version: 1.6.13~64bit ( 64bit) / Fusion HEAD git clone April 10.  Didn't notice the login error until fail2ban blocked the client requiring fresh login after getting that resolved.  I am also getting the string array errors, though on a different line. Selecting edit on the Inbound route results in:    
Fatal error: Uncaught Error: Cannot use string offset as an array in /usr/local/www/fusionpbx/app/dialplan/dialplan_edit.php:231 Stack trace: #0 {main} thrown in /usr/local/www/fusionpbx/app/dialplan/dialplan_edit.php on line 231
I thought I had done something wrong so I deleted it and recreated it twice, once through a destination, the current one through an IVR. Seems to work as long as you don't try to edit it.

**Comment by markjcrane** [comment] 2017-04-13 00:03
Fail2ban will not change the user password it blocks access only with iptables. 
Dialplan Edit I will give that a try on my FreeBSD installs. 

For most cases you should be creating your inbound routes with Dialplan -> Destinations.

**Comment by tonyhain** [comment] 2017-04-13 04:24
I couldn't get the compiled greeting to play when I when through destinations, but after switching to the IVR and getting only an exit sound, I figured out that the compiled wav files were exported 32bit, so I resampled them to 16. I haven't gone back yet since the IVR mechanism is working. In any case, there is another problem in Outbound Routes. I created a gateway for the 3102, then an outbound route with 
GTW:  56d33a44-d7e4-4bd6-b544-3be2ceeda15f:3102FXO
the shortcut 911   ->    ^(911)$ 
and a limit of 1 channel
but that resulted in:
Fatal error: Uncaught ArgumentCountError: Too few arguments to function dialplan_detail_add(), 7 passed in /usr/local/www/fusionpbx/app/dialplan_outbound/dialplan_outbound_add.php on line 385 and exactly 9 expected in /usr/local/www/fusionpbx/resources/switch.php:643 Stack trace: #0 /usr/local/www/fusionpbx/app/dialplan_outbound/dialplan_outbound_add.php(385): dialplan_detail_add('1261c653-9a03-4...', '33784d15-c9ec-4...', 'condition', '005', '0', 'destination_num...', '^(911)$') #1 {main} thrown in /usr/local/www/fusionpbx/resources/switch.php on line 643

I got the same error with other shortcuts, but I figured that was the simplest one.

I don't really want to use the Gateway mechanism since the 3102 won't accept a regsiter from the pbx (Zopier gets 501 not-implemented response), but the 3102 registers itself fine as extension 102. When I tried this last month I never could get FusionPBX to even try via the stopped gateway (since the registration doesn't work outbound), or when Register false was set. With Asterisk all i did was something like: 
exten => _+1[2-9]xxxxxxxxx,n,Dial(SIP/${EXTEN:1}@${PSTNGW1}:5061)
where $PSTNGW1 was defined as the IPv4 address of the 3102.  What I was looking for in Outbound Routes was the ability to transfer via ext 102, but the transfer option doesn't really allow that (you can edit the transfer xml line before saving, but when you reopen the edit, the change is gone). Since the 3102 FXO port is listening on 5061, and there is no obvious way to set that in FusionPBX (the x.x.x.x:5061 thing is not rejected, but never mentioned in the docs or ui), it could be the auth failure is simply not connecting. But tcpdump is not showing ANY packets going to the 3102 except the registrations for line 101 & 102 initiated by the 3102. Expire is set to 5 and retry to 2, and still no packets being sent out. That says FusionPBX is not even trying to auth.  Log shows nothing about the outbound registrations either:

Displaying the last 32,768 of 3,409,015 bytes.
2017-04-12 17:54:17.389981 [WARNING] sofia_reg.c:1792 SIP auth challenge (REGISTER) on sofia profile 'internal' for [102@voice.hain-global-consulting.com] from ip 172.16.144.60 
2017-04-12 17:54:17.370746 [WARNING] sofia_reg.c:1792 SIP auth challenge (REGISTER) on sofia profile 'internal' for [101@voice.hain-global-consulting.com] from ip 172.16.144.60 
2017-04-12 17:53:35.210674 [WARNING] switch_core_file.c:352 File has 2 channels, muxing to 1 channel will occur. 
2017-04-12 17:53:22.530918 [WARNING] switch_core_file.c:352 File has 2 channels, muxing to 1 channel will occur. 
2017-04-12 17:53:03.430841 [WARNING] switch_core_file.c:352 File has 2 channels, muxing to 1 channel will occur. 
2017-04-12 17:52:51.809502 [WARNING] switch_core_file.c:352 File has 2 channels, muxing to 1 channel will occur. 
2017-04-12 17:52:25.850610 [WARNING] sofia_reg.c:1792 SIP auth challenge (REGISTER) on sofia profile 'internal' for [1001@voice.hain-global-consulting.com] from ip 172.28.194.87 
2017-04-12 17:52:23.290217 [WARNING] sofia_reg.c:1792 SIP auth challenge (REGISTER) on sofia profile 'internal' for [2001@voice.hain-global-consulting.com] from ip 172.24.144.29 
2017-04-12 17:52:02.908811 [WARNING] sofia_reg.c:1792 SIP auth challenge (REGISTER) on sofia profile 'internal' for [1003@voice.hain-global-consulting.com] from ip 172.24.144.42 
2017-04-12 17:51:48.390630 [WARNING] switch_core_file.c:352 File has 2 channels, muxing to 1 channel will occur. 
2017-04-12 17:51:48.390630 [WARNING] switch_core_file.c:352 File has 2 channels, muxing to 1 channel will occur. 
2017-04-12 17:51:48.390630 [WARNING] switch_core_file.c:352 File has 2 channels, muxing to 1 channel will occur. 
SQL [Enabled] 
Session Rate [30] 
Max Sessions [1000] 
FreeSWITCH Started 

FreeSWITCH Version 1.6.16+git~20170410T202705Z~1769905709~64bit (git 1769905 2017-04-10 20:27:05Z 64bit) 
2017-04-12 17:51:47.434088 [INFO] switch_core.c:2435 
2017-04-12 17:51:47.434088 [NOTICE] switch_utils.c:545 Adding 192.168.42.42/32 (allow) [] to list lan 
2017-04-12 17:51:47.434088 [WARNING] switch_core.c:1609 Cannot locate domain 172.20.160.51 
2017-04-12 17:51:47.434088 [DEBUG] freeswitch_lua.cpp:382 DBH handle 0x8099d40f0 released. 
2017-04-12 17:51:47.434088 [DEBUG] freeswitch_lua.cpp:365 DBH handle 0x8099d40f0 Connected. 
2017-04-12 17:51:47.409461 [DEBUG] freeswitch_lua.cpp:382 DBH handle 0x8099d40f0 released. 
2017-04-12 17:51:47.409461 [DEBUG] freeswitch_lua.cpp:365 DBH handle 0x8099d40f0 Connected. 
2017-04-12 17:51:47.338010 [DEBUG] mod_spandsp_fax.c:191 FAX timer thread started. 
2017-04-12 17:51:47.304387 [DEBUG] mod_event_socket.c:2943 Socket up listening on 127.0.0.1:8021 
2017-04-12 17:51:47.301971 [DEBUG] switch_loadable_module.c:735 Chat Thread Started 
2017-04-12 17:51:47.301909 [DEBUG] switch_loadable_module.c:735 Chat Thread Started 
2017-04-12 17:51:47.301869 [INFO] switch_time.c:615 Clock synchronized to system time. 


Clearly one of the audio files is not mono, but figuring out which one is 352 will be a PITA.

**Comment by tonyhain** [comment] 2017-04-13 05:42
tried to edit *9172 and got back:
Fatal error: Uncaught Error: Cannot use string offset as an array in /usr/local/www/fusionpbx/app/dialplan/dialplan_edit.php:231 Stack trace: #0 {main} thrown in /usr/local/www/fusionpbx/app/dialplan/dialplan_edit.php on line 231

**Comment by markjcrane** [comment] 2017-04-13 06:50
Odd since when I run it works fine. You said you ate running freebsd?  I may need temp access to solve the issue since I can't duplicate it.

**Comment by hpandroid** [comment] 2017-04-13 14:49
Hi Mark,

I installed in windows, First I installed Freeswitch from FreeSWITCH-1.6.16-x64-Release.msi
This installation location is C:\Program Files\FreeSWITCH
I downloaded fusionpbx from master copy, and copied it in to iis webroot.
When i browse the website first time it is showed me installation page. I followed the steps. finally after giving the Database connection details it keep on loading and after a few min it ended up with error saying that Mysql server went away. error occurred at menu.php at line 441.  

I tied to browse the installation url it is working good but the problem is i was able to edit some configurations. But What I findout after seeing this dial panel error is when ever i try  editing the configuration it is updating configuration files exit in fusionpbx webroot app folder but when i try to edit XML files it is editing at the FreeSwitch  installation location(ProgramFiles/FreeSwitch/app). I do not understand how freeswitch is going to use these configuration files from two different locations.

Thanks,
Harry.

**Comment by hpandroid** [comment] 2017-04-13 17:54
Hi Mark,

I think this Fatal error: Uncaught Error: Cannot use string offset as an array in C:\inetpub\wwwroot\fusionpbx\app\dialplan\dialplan_edit.php:249 Stack trace: #0 {main} thrown in C:\inetpub\wwwroot\fusionpbx\app\dialplan\dialplan_edit.php on line 249 issue is causing by php v7.2. I checked with php5.6.30 and it is good and problem disappeared.

Thanks,
Harry

**Comment by hpandroid** [comment] 2017-04-13 17:58
Hi Rossbcan,

Have find the problem with PHP Fatal error: Call to a member function execute() on a non-object in /usr/local/fusionpbx/resources/classes/menu.php on line 441.  At the time of installation i saw this error but i really have no clue what it is going to effect. if you figured out what causing this issue please let me know so that i can fix it.

Thanks,
Harry
